# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.resize(360, 200)
        windowaviso.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(-110, 140, 360, 32))
        self.btnBoxAviso.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setCenterButtons(False)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.lblAviso = QtWidgets.QLabel(windowaviso)
        self.lblAviso.setGeometry(QtCore.QRect(110, 90, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblAviso.setFont(font)
        self.lblAviso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAviso.setObjectName("lblAviso")
        self.lblmageAviso = QtWidgets.QLabel(windowaviso)
        self.lblmageAviso.setGeometry(QtCore.QRect(120, 20, 91, 71))
        self.lblmageAviso.setText("")
        self.lblmageAviso.setTextFormat(QtCore.Qt.PlainText)
        self.lblmageAviso.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.lblmageAviso.setScaledContents(True)
        self.lblmageAviso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblmageAviso.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lblmageAviso.setObjectName("lblmageAviso")

        self.retranslateUi(windowaviso)
        self.btnBoxAviso.accepted.connect(windowaviso.accept)
        self.btnBoxAviso.rejected.connect(windowaviso.reject)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Dialog"))
        self.lblAviso.setText(_translate("windowaviso", "Desea salir?"))

