# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(839, 605)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(300, 180, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 210, 158, 54))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAceptar = QtWidgets.QPushButton(self.widget)
        self.btnAceptar.setObjectName("btnAceptar")
        self.gridLayout.addWidget(self.btnAceptar, 1, 0, 1, 1)
        self.btnSalir = QtWidgets.QPushButton(self.widget)
        self.btnSalir.setObjectName("btnSalir")
        self.gridLayout.addWidget(self.btnSalir, 1, 1, 1, 1)
        self.txtDatos = QtWidgets.QLineEdit(self.widget)
        self.txtDatos.setObjectName("txtDatos")
        self.gridLayout.addWidget(self.txtDatos, 0, 0, 1, 2)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAbrir = QtWidgets.QMenu(self.menuArchivo)
        self.menuAbrir.setObjectName("menuAbrir")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.actionGuadar = QtWidgets.QAction(window)
        self.actionGuadar.setObjectName("actionGuadar")
        self.actionGuardar_Como = QtWidgets.QAction(window)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.actionFichero = QtWidgets.QAction(window)
        self.actionFichero.setObjectName("actionFichero")
        self.actionSalir = QtWidgets.QAction(window)
        self.actionSalir.setObjectName("actionSalir")
        self.menuAbrir.addAction(self.actionFichero)
        self.menuArchivo.addAction(self.menuAbrir.menuAction())
        self.menuArchivo.addAction(self.actionGuadar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.lblTitulo.setText(_translate("window", "MI PRIMERA VENTANA"))
        self.btnAceptar.setText(_translate("window", "Aceptar"))
        self.btnSalir.setText(_translate("window", "Salir"))
        self.menuArchivo.setTitle(_translate("window", "Archivo"))
        self.menuAbrir.setTitle(_translate("window", "Abrir"))
        self.actionGuadar.setText(_translate("window", "Guadar"))
        self.actionGuardar_Como.setText(_translate("window", "Guardar Como"))
        self.actionFichero.setText(_translate("window", "Fichero"))
        self.actionSalir.setText(_translate("window", "Salir"))
